### ISSUE TITLE
录播上传登陆的时候会被 B 站风控

### ISSUE THREAD

**Issue by Magic-Xin** [chocotan/bili-recorder#3]
log 如下，已隐去个人信息

> 2021-12-14 17:15:59.563  INFO 7 --- [scheduling-2] m.c.recorder.utils.HttpClientUtil        : url=https://passport.bilibili.com/x/passport-login/oauth2/login, header={"Device-ID":"...","Buvid":"...","Display-ID":" xxx","User-Agent":"Mozilla/5.0 BiliDroid/5.37.0 (bbcallen@gmail.com)"}, param={appkey=xxx, build=5370000, challenge=, channel=html5_app_bili, mobi_app=android, password=..., platform=android, seccode=, sign=xxx, ts=1639473359, username=..., validate=}, resp={"code":0,"message":"0","ttl":1,"data":{"status":2,"message":"本次登录环境存在风险, 需使用手机号进行验证或绑定","url":"https://passport.bilibili.com/account/mobile/security/managephone/phone/verify?tmp_token=...\u0026requestId=...\u0026source=risk","token_info":null,"cookie_info":null,"sso":null}}

**Comment by Magic-Xin** [comment]
补充一下 log

> 2021-12-14 17:24:00.893  INFO 7 --- [scheduling-4] moe.chikalar.recorder.job.UploadJob      : [1] 上传录播异常，等待下次重试，error=java.lang.NullPointerException
	at moe.chikalar.recorder.api.BiliApi.getKeyAndLogin(BiliApi.java:204)
	at moe.chikalar.recorder.uploader.BiliVideoUploader.upload2(BiliVideoUploader.java:59)
	at moe.chikalar.recorder.job.UploadJob.uploadCheck(UploadJob.java:150)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by chocotan** [comment]
用的登录接口被b站给封了, 我再调试一下


MagicXin ***@***.***> 于2021年12月14日周二 17:36写道：

**Comment by chocotan** [comment]
查了半天, 没搞定, 等别人搞好我去抄吧, 唉

**Comment by chocotan** [comment]
密码登录接口应该是全部不能用了，切换到了TV app的扫码登录接口，不知道能存活多久
我自己现在不当录播man了，如果后续b站再调整api我大概不会再修了

**Comment by Magic-Xin** [comment]
感谢维护
